before_script:
    - ruby -v
    - gem update --system
    - gem install bundler -v '~>1.13'
    - bundler --version
    - make

stages:
    - release

release_gem:
    image: ruby:2.3
    stage: release
    environment: release
    only:
        - tags
    script:
        - mkdir -p ~/.gem
        - 'printf "%s\n:rubygems_api_key: %s" "---" "${RUBYGEMSORG_API_KEY}" > ~/.gem/credentials; chmod 0600 ~/.gem/credentials'
        - make release
