before_script:
    - gem update --system
    - gem install bundler -v '~>1.13'
    - bundler --version
    - bundler install

stages:
    - release

release:
    image: ruby:2.4
    stage: release
    environment: gem
    only:
        - tags
    script:
        - mkdir -p ~/.gem
        - 'printf "%s\n:rubygems_api_key: %s" "---" "${RUBYGEMSORG_API_KEY}" > ~/.gem/credentials; chmod 0600 ~/.gem/credentials'
        - ./bin/release.sh
